[package]
version = "0.1.0"
name = "mina_bridge_sp1-compress"
edition = "2021"

[dependencies]
sp1-sdk.workspace = true
bincode.workspace = true
kimchi-verifier-ffi = { path = "../lib/" }

[build-dependencies]
sp1-helper.workspace = true
