[package]
name = "contract_deployer"
version = "0.1.0"
edition = "2021"

[dependencies]
mina_bridge_core = { path = "../core/" }
tokio = "1.39.1"
env_logger = "0.11.5"
log = "0.4.22"
ethers = { tag = "v2.0.15-fix-reconnections", features = [
  "ws",
  "rustls",
  "solc",
], git = "https://github.com/yetanotherco/ethers-rs.git" }
mina-curves = { git = "https://github.com/lambdaclass/openmina-proof-systems", branch = "mina_bridge" }
o1-utils = { git = "https://github.com/lambdaclass/proof-systems", branch = "add-verifier-serializations" }
kimchi = { git = "https://github.com/lambdaclass/openmina-proof-systems", branch = "mina_bridge" }
aligned-sdk = { git = "https://github.com/lambdaclass/aligned_layer.git", branch = "update_batcher_deps" }
serde = { version = "1.0", features = ["derive"] }
mina-p2p-messages = { git = "https://github.com/lambdaclass/openmina/", branch = "mina_bridge" }
bincode = "1.3.3"
serde_with = "1.10.0"

[patch.crates-io]
ark-ff = { git = "https://github.com/openmina/algebra", branch = "openmina" }
ark-ec = { git = "https://github.com/openmina/algebra", branch = "openmina" }
ark-poly = { git = "https://github.com/openmina/algebra", branch = "openmina" }
ark-serialize = { git = "https://github.com/openmina/algebra", branch = "openmina" }
