[package]
name = "contract_deployer"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../core/" }
tokio = "1.39.1"
env_logger = "0.11.5"
log = "0.4.22"
ethers = { tag = "v2.0.15-fix-reconnections", features = [
  "ws",
  "rustls",
  "solc",
], git = "https://github.com/yetanotherco/ethers-rs.git" }
mina-curves = { git = "https://github.com/openmina/proof-systems", branch = "ledger-newtypes-rampup4-vrf" }
o1-utils = { git = "https://github.com/lambdaclass/proof-systems", branch = "add-verifier-serializations" }
kimchi = { git = "https://github.com/openmina/proof-systems", branch = "ledger-newtypes-rampup4-vrf" }
aligned-sdk = { git = "https://github.com/lambdaclass/aligned_layer.git", branch = "account_inclusion_verifier" }

[patch.crates-io]
ark-ff = { git = "https://github.com/openmina/algebra", branch = "openmina" }
ark-ec = { git = "https://github.com/openmina/algebra", branch = "openmina" }
ark-poly = { git = "https://github.com/openmina/algebra", branch = "openmina" }
ark-serialize = { git = "https://github.com/openmina/algebra", branch = "openmina" }
