[package]
version = "0.1.0"
name = "mina_bridge_sp1-prove"
edition = "2021"

[dependencies]
sp1-sdk.workspace = true
kimchi-verifier-ffi = { path = "../lib/" }
bincode.workspace = true

[build-dependencies]
sp1-helper.workspace = true
