[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = false
fs_permissions = [
    { access = "read", path = "./proof.mpk"},
    { access = "read", path = "./state.mpk"},
    { access = "read", path = "./urs.mpk"},
    { access = "read", path = "./verifier_index.mpk"},
    { access = "read", path = "./prover_proof.mpk"},
    { access = "read", path = "./public_inputs.mpk"},
    { access = "read", path = "./linearization.mpk"},
    { access = "read", path = "./unit_test_data/"},
    { access = "read-write", path = "./linearization.rlp"}
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
