[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
fs_permissions = [
    { access = "read", path = "./proof.mpk"},
    { access = "read", path = "./state.mpk"},
    { access = "read", path = "./urs.mpk"},
    { access = "read", path = "./verifier_index.mpk"},
    { access = "read", path = "./prover_proof.mpk"},
    { access = "read", path = "./prover_proof.bin"},
    { access = "read", path = "./public_inputs.mpk"},
    { access = "read", path = "./linearization.mpk"},
    { access = "read", path = "./lagrange_bases.mpk"},
    { access = "read", path = "./unit_test_data/"},
    { access = "read-write", path = "./linearization.rlp"}
]
solc = "0.8.21"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[etherscan]
#                 Paste TENDERLY_ACCESS_KEY      Chain ID          Verification URL: RPC_URL/verify/etherscan
unknown_chain = { key = "R5rG-xNm1X40p9PmEmCE1b7wp25Yi8hK", chain = 11155111, url = "https://api.tenderly.co/api/v1/account/lambdaclassinfra/project/kimchi-evm-verifier/etherscan/verify/devnet/9f4251c0-0f34-4d62-99b4-89d21e35e454" }
