[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
fs_permissions = [
    { access = "read", path = "./verifier_index.bin"},
    { access = "read", path = "./prover_proof.bin"},
    { access = "read", path = "./public_input.bin"},
    { access = "read", path = "./merkle_path.bin"},
    { access = "read", path = "./merkle_root.bin"},
    { access = "read", path = "./merkle_leaf.bin"},
    { access = "read", path = "./test_merkle_path.bin"},
    { access = "read", path = "./linearization.bin"},
    { access = "read", path = "./linearization_literals.bin"},
    { access = "read", path = "./unit_test_data/"},
]
# https://github.com/foundry-rs/foundry/issues/6780#issuecomment-1962319449
bytecode_hash = "none"
cbor_metadata = false
sparse_mode = false

[profile.default.optimizer_details]
# constantOptimizer = true
yul = true
