[package]
name = "testsandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
js-sandbox = { git = "https://github.com/gempoint/js-sandbox.git" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
